### ISSUE TITLE
Failed to create the very first profile

### ISSUE THREAD

**Issue by pavel-alay** [tonsky/sublime-profiles#3]
The plugin does not respond on creation the very first profile.

From the console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1201, in preview_
    ret = self.preview(v)
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Installed Packages/Profile Switcher.sublime-package/profiles.py", line 42, in preview
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Installed Packages/Profile Switcher.sublime-package/profiles.py", line 28, in profiles
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pavel/Library/Application Support/Sublime Text 3/Packages/sublime-profiles/Data'
```

It works as expected after manual creation of the Data directory.

Sublime Text 4, macOS 10.15.7.

**Comment by tonsky** [comment]
Thank you! Hopefully fixed
